name: Compile and release

on:
  push:
    branches:
      main
    paths:
      car.txt

env:
  PLUGIN_NAME: tf2_defenderbots

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sm-version: [ '1.12.7164', '1.13.7166' ]
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set environment variables
        run: echo SCRIPTS_PATH=$(pwd) >> $GITHUB_ENV

      - name: Setup SourcePawn Compiler ${{ matrix.sm-version }}
        id: setup_sp
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.sm-version }}
          version-file: ./source/${{ env.PLUGIN_NAME }}.sp

      - name: Download the includes downloader
        uses: tsuza/SPDependy@v2
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          output_directory: "${{ env.SCRIPTS_PATH }}/source/include"

      - name: Compile plugins
        run: |
          mkdir ../plugins
          spcomp -v2 -i "include" -o"../plugins/${{ env.PLUGIN_NAME }}.smx" ${{ env.PLUGIN_NAME }}.sp
          echo "===OUT FILES==="
          ls ../plugins
          echo "===VERSION==="
          echo ${{ steps.setup_sp.outputs.plugin-version }}
        working-directory: ${{ env.SCRIPTS_PATH }}/source

      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Zip output
        run: |
          zip -qq -y -r ${{ github.event.repository.name }}-sm${{ matrix.sm-version }}.zip configs gamedata plugins
        working-directory: ${{ env.SCRIPTS_PATH }}

      - name: List files in the directory
        run: ls -R
        working-directory: ${{ env.SCRIPTS_PATH }}

      - name: List files in the zip
        run: unzip -l ${{ github.event.repository.name }}-sm${{ matrix.sm-version }}.zip
        working-directory: ${{ env.SCRIPTS_PATH }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.setup_sp.outputs.plugin-version }}
          artifacts: ${{ github.event.repository.name }}-sm${{ matrix.sm-version }}.zip
          draft: true
          allowUpdates: true
          updateOnlyUnreleased: true
